name: cargo pgrx tests
on:
  - push
jobs:
  tests:
#    strategy:
#      matrix:
#        pg_version: [13, 14, 15, 16, 17, 18]
    runs-on: host
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: cargo pgrx test
        # run: cargo pgrx test pg${{matrix.pg_version}}
        run: make test_all
