name: tests
on:
  - push
jobs:
  tests:
    container:
      image: ghcr.io/catthehacker/ubuntu:runner-latest
    strategy:
      matrix:
        pg_version: [13, 14, 15, 16, 17, 18]
        os: [ubuntu-latest] #[ ubuntu-latest, centos-latest]
    runs-on: ${{matrix.os}}
    env:
      POSTGRES_VERSION: ${{matrix.pg_version}}
    steps:
      - name: install  apt  deps
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt update -y && sudo apt install -y rustup flex bison pkg-config  libssl-dev libreadline-dev zlib1g-dev libclang-dev clang
      - name: install rpm deps
        if: contains(matrix.os, 'centos')
        run: |
          echo TBD
      - run: rustup default stable
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: make install_pgrx
      - run: make clean
      - run: make init_download
      - run: make test
