name: PG_ENIGMA for pg16 tests
on:
  - push
# env:
#   PGRX_HOME: /root/.pgrx
#   RUST_BACKTRACE: full
jobs:
  tests:
    strategy:
      matrix:
        pg_version: [16] # [16,17,18]
        os: [ubuntu-latest] #[ ubuntu-latest, centos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: install  apt  deps
        if: contains(matrix.os, 'ubuntu')
        run: |
          apt update -y && apt install -y rustup flex bison pkg-config  libssl-dev libreadline-dev zlib1g-dev libclang-dev clang
      - name: install rpm deps
        if: contains(matrix.os, 'centos')
        run: |
          echo TBD
      - run: rustup default stable
      - run:  cargo install --locked cargo-pgrx
      - name: Check out repository code
        uses: actions/checkout@v5
      - run:  cargo pgrx init --pg${{ matrix.pg_version}} download
      - run: |
          export PGRX_PG_CONFIG_PATH=$(find $PGRX_HOME/${{matrix.pg_version}}*/pgrx-install/ -name pg_config)
          cargo pgrx  test pg${{matrix.pg_version}}
