name: PG_ENIGMA for pg16 tests
on:
  - push
env:
  PGRX_HOME: /root/.pgrx
  RUST_BACKTRACE: full
jobs:
  tests_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [16, 17, 18]
    steps:
      - run: pwd
      - run: apt update -y 
      - name: install deps
        run: |
          apt install -y rustup libclang-dev clang build-essential libreadline-dev \
              zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev \
              libxml2-utils xsltproc ccache pkg-config
      - run:  cargo install --locked cargo-pgrx
      - name: Check out repository code
        uses: actions/checkout@v5
      - run:  cargo pgrx init --pg${matrix.pg_version} download
      - run:  cargo pgrx  test pg16
        env: 
          PGRX_PG_CONFIG_PATH: $PGRX_HOME/16.11/pgrx-install/bin/pg_config
