name: PG_ENIGMA for pg16 tests
on:
  - push
env:
  PGRX_HOME: /root/.pgrx
  RUST_BACKTRACE: full
jobs:
  tests:
    strategy:
      matrix:
        pg_version: [16] # [16,17,18]
        os: [ubuntu-latest] #[ ubuntu-latest, centos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: install  apt  deps
        if: contains(runner.os, 'ubuntu')
        run: |
          apt update -y 
          apt install -y rustup libclang-dev clang build-essential libreadline-dev \
              zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev \
              libxml2-utils xsltproc ccache pkg-config
      - name: install rpm deps
        if: contains(runner.os, 'centos')
        run: |
          echo TBD
      - run: rustup default stable
      - run:  cargo install --locked cargo-pgrx
      - name: Check out repository code
        uses: actions/checkout@v5
      - run:  cargo pgrx init --pg${{ matrix.pg_version}} download
      - run: |
          export PGRX_PG_CONFIG_PATH=$(find $PGRX_HOME/${{matrix.pg_version}}* -name pg_config)
          echo $PGRX_PG_CONFIG_PATH
          cargo pgrx  test pg${{matrix.pg_version}}
