name: tests
on:
  - push
jobs:
  tests:
    strategy:
      matrix:
        pg_version: [16] # [16,17,18]
        os: [ubuntu-latest] #[ ubuntu-latest, centos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - run: |
          useradd  -m dev
          sudo sh -c 'echo "dev ALL=(ALL) ALL" >> /etc/sudoers'

      - name: install  apt  deps
        if: contains(matrix.os, 'ubuntu')
        run: |
          apt update -y && apt install -y rustup flex bison pkg-config  libssl-dev libreadline-dev zlib1g-dev libclang-dev clang
      - name: install rpm deps
        if: contains(matrix.os, 'centos')
        run: |
          echo TBD
      - run: rustup default stable
      - run:  cargo install --locked cargo-pgrx
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: pgrx init 
        if: steps.cache.outputs.cache-hit != 'true'
        run:  cargo pgrx init --pg${{ matrix.pg_version}} download
      - run: |
          export PGRX_PG_CONFIG_PATH=$(cargo pgrx info pg-config pg${{matrix.pg_version}})
          cargo pgrx  test --runas dev pg${{ matrix.pg_version }} 
